"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INVALID_OTP = exports.EXPIRED = exports.EXHAUSTED_RETRIES = exports.OTP_INVALID_MESSAGE = exports.EXPIRED_MESSAGE = exports.RETRIES_EXHAUSTED_MESSAGE = exports.DEFAULT_VERIFICATION_ERROR_MESSAGE = exports.DEFAULT_VERIFICATION_ERROR_NAME = void 0;
exports.DEFAULT_VERIFICATION_ERROR_NAME = "EmailOtpVerificationError";
exports.DEFAULT_VERIFICATION_ERROR_MESSAGE = "Email OTP verification failed";
exports.RETRIES_EXHAUSTED_MESSAGE = "Email OTP verification failed: Retries exhausted";
exports.EXPIRED_MESSAGE = "Email OTP verification failed: Expired";
exports.OTP_INVALID_MESSAGE = "Email OTP verification failed: Invalid OTP";
exports.EXHAUSTED_RETRIES = { exhaustedRetries: true };
exports.EXPIRED = { expired: true };
exports.INVALID_OTP = { invalid: true };
